name: build-workflow

# Controls when the workflow will run
on:

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Allows for ruese in other workflows
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      - name: Install dependencies
        run: dotnet restore ./src/webapi

      - name: Build webapi
        run: dotnet build ./src/webapi --configuration Release --no-restore

      - name: Test webapi
        run: dotnet test ./src/webapi-tests --verbosity minimal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
